PROJECT_ROOT := $(shell pwd)

Q ?= @ 

COMMON_FLAGS := 

CXX_FLAGS := 

LD_FLAGS := 

LIBRARIES := openblas lightblas 

LIBRARY_DIRS := $(PROJECT_ROOT)/local/lib

INCLUDE_DIRS := $(PROJECT_ROOT)/local/include

CXX := g++

AR := ar
